/**
 * Language utilities for code viewers.
 * Maps file extensions to Monaco editor IDs and human-readable display names.
 */

const MONACO_LANGUAGE_MAP: Record<string, string> = {
  '.js': 'javascript',
  '.jsx': 'javascript',
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.py': 'python',
  '.java': 'java',
  '.cpp': 'cpp',
  '.c': 'c',
  '.h': 'c',
  '.hpp': 'cpp',
  '.cs': 'csharp',
  '.php': 'php',
  '.rb': 'ruby',
  '.go': 'go',
  '.rs': 'rust',
  '.swift': 'swift',
  '.kt': 'kotlin',
  '.scala': 'scala',
  '.html': 'html',
  '.htm': 'html',
  '.css': 'css',
  '.scss': 'scss',
  '.sass': 'sass',
  '.less': 'less',
  '.xml': 'xml',
  '.json': 'json',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'toml',
  '.ini': 'ini',
  '.cfg': 'ini',
  '.conf': 'ini',
  '.sh': 'shell',
  '.bash': 'shell',
  '.zsh': 'shell',
  '.fish': 'shell',
  '.sql': 'sql',
  '.r': 'r',
  '.m': 'matlab',
  '.mat': 'matlab',
  '.ipynb': 'json',
  '.jl': 'julia',
  '.dart': 'dart',
  '.lua': 'lua',
  '.pl': 'perl',
  '.pm': 'perl',
  '.tcl': 'tcl',
  '.vbs': 'vb',
  '.ps1': 'powershell',
  '.bat': 'batch',
  '.cmd': 'batch',
  '.coffee': 'coffeescript',
  '.litcoffee': 'coffeescript',
  '.iced': 'coffeescript',
  '.md': 'markdown',
  '.markdown': 'markdown',
  '.tex': 'latex',
  '.rtex': 'latex',
  '.bib': 'bibtex',
  '.vue': 'vue',
  '.svelte': 'svelte',
}

const DISPLAY_LANGUAGE_MAP: Record<string, string> = {
  '.js': 'JavaScript',
  '.jsx': 'JavaScript',
  '.ts': 'TypeScript',
  '.tsx': 'TypeScript',
  '.py': 'Python',
  '.java': 'Java',
  '.cpp': 'C++',
  '.c': 'C',
  '.h': 'C',
  '.hpp': 'C++',
  '.cs': 'C#',
  '.php': 'PHP',
  '.rb': 'Ruby',
  '.go': 'Go',
  '.rs': 'Rust',
  '.swift': 'Swift',
  '.kt': 'Kotlin',
  '.scala': 'Scala',
  '.html': 'HTML',
  '.htm': 'HTML',
  '.css': 'CSS',
  '.scss': 'SCSS',
  '.sass': 'Sass',
  '.less': 'Less',
  '.xml': 'XML',
  '.json': 'JSON',
  '.yaml': 'YAML',
  '.yml': 'YAML',
  '.toml': 'TOML',
  '.ini': 'INI',
  '.cfg': 'INI',
  '.conf': 'INI',
  '.sh': 'Shell',
  '.bash': 'Bash',
  '.zsh': 'Zsh',
  '.fish': 'Fish',
  '.sql': 'SQL',
  '.r': 'R',
  '.m': 'MATLAB',
  '.mat': 'MATLAB',
  '.ipynb': 'Jupyter Notebook',
  '.jl': 'Julia',
  '.dart': 'Dart',
  '.lua': 'Lua',
  '.pl': 'Perl',
  '.pm': 'Perl',
  '.tcl': 'TCL',
  '.vbs': 'VBScript',
  '.ps1': 'PowerShell',
  '.bat': 'Batch',
  '.cmd': 'Batch',
  '.coffee': 'CoffeeScript',
  '.litcoffee': 'CoffeeScript',
  '.iced': 'CoffeeScript',
  '.md': 'Markdown',
  '.markdown': 'Markdown',
  '.tex': 'LaTeX',
  '.rtex': 'LaTeX',
  '.bib': 'BibTeX',
  '.vue': 'Vue',
  '.svelte': 'Svelte',
}

function getExtension(fileName: string): string {
  return fileName.toLowerCase().substring(fileName.lastIndexOf('.'))
}

export function getLanguageMonacoId(fileName: string): string {
  return MONACO_LANGUAGE_MAP[getExtension(fileName)] ?? 'plaintext'
}

export function getLanguageDisplayName(fileName: string): string {
  return DISPLAY_LANGUAGE_MAP[getExtension(fileName)] ?? 'Plain Text'
}
