import { Theme } from '../types/slide-layouts'

export const curatedThemes: Theme[] = [
  // Professional Business Themes
  {
    id: 'professional-blue-gradient',
    name: 'Professional Blue',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#1e3c72',
      endColor: '#2a5298',
      angleDeg: 135,
    },
    colorPalette: {
      primary: '#1e3c72',
      secondary: '#2a5298',
      accent: '#4a90e2',
      text: '#ffffff',
      textSecondary: '#e8f4f8',
      background: '#1e3c72',
    },
    decorativeElements: [
      {
        id: 'circle-1',
        shape: 'circle',
        x: 85,
        y: 15,
        width: 20,
        height: 20,
        color: '#4a90e2',
        opacity: 0.1,
      },
      {
        id: 'circle-2',
        shape: 'circle',
        x: 10,
        y: 80,
        width: 15,
        height: 15,
        color: '#ffffff',
        opacity: 0.05,
      },
    ],
    typography: {
      titleFont: 'Inter, sans-serif',
      titleSize: 48,
      titleWeight: 700,
      bodyFont: 'Inter, sans-serif',
      bodySize: 18,
      bodyWeight: 400,
    },
    metadata: {
      category: 'professional',
      tags: ['business', 'corporate', 'gradient'],
      description: 'Professional blue gradient theme perfect for business presentations',
    },
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    backgroundStyle: {
      kind: 'solid',
      color: '#ffffff',
    },
    colorPalette: {
      primary: '#000000',
      secondary: '#f5f5f5',
      accent: '#2563eb',
      text: '#1f2937',
      textSecondary: '#6b7280',
      background: '#ffffff',
    },
    decorativeElements: [
      {
        id: 'line-1',
        shape: 'line',
        x: 0,
        y: 20,
        width: 100,
        height: 2,
        color: '#2563eb',
        opacity: 1,
      },
    ],
    typography: {
      titleFont: 'Inter, sans-serif',
      titleSize: 42,
      titleWeight: 600,
      bodyFont: 'Inter, sans-serif',
      bodySize: 16,
      bodyWeight: 400,
    },
    metadata: {
      category: 'minimal',
      tags: ['clean', 'simple', 'modern'],
      description: 'Clean and minimal design with subtle accents',
    },
  },
  {
    id: 'warm-sunset',
    name: 'Warm Sunset',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#ff6b6b',
      endColor: '#ffa500',
      angleDeg: 45,
    },
    colorPalette: {
      primary: '#ff6b6b',
      secondary: '#ffa500',
      accent: '#ffd93d',
      text: '#ffffff',
      textSecondary: '#fff5e6',
      background: '#ff6b6b',
    },
    decorativeElements: [
      {
        id: 'blob-1',
        shape: 'blob',
        x: 70,
        y: 10,
        width: 30,
        height: 30,
        color: '#ffd93d',
        opacity: 0.2,
        rotation: 15,
      },
    ],
    typography: {
      titleFont: 'Poppins, sans-serif',
      titleSize: 44,
      titleWeight: 700,
      bodyFont: 'Poppins, sans-serif',
      bodySize: 17,
      bodyWeight: 400,
    },
    metadata: {
      category: 'colorful',
      tags: ['warm', 'energetic', 'vibrant'],
      description: 'Warm and energetic gradient perfect for creative presentations',
    },
  },
  {
    id: 'dark-modern',
    name: 'Dark Modern',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#0f0c29',
      endColor: '#302b63',
      angleDeg: 180,
    },
    colorPalette: {
      primary: '#0f0c29',
      secondary: '#302b63',
      accent: '#6c5ce7',
      text: '#ffffff',
      textSecondary: '#dfe6e9',
      background: '#0f0c29',
    },
    decorativeElements: [
      {
        id: 'circle-dark-1',
        shape: 'circle',
        x: 80,
        y: 20,
        width: 25,
        height: 25,
        color: '#6c5ce7',
        opacity: 0.15,
      },
      {
        id: 'circle-dark-2',
        shape: 'circle',
        x: 15,
        y: 75,
        width: 20,
        height: 20,
        color: '#ffffff',
        opacity: 0.05,
      },
    ],
    typography: {
      titleFont: 'Roboto, sans-serif',
      titleSize: 46,
      titleWeight: 700,
      bodyFont: 'Roboto, sans-serif',
      bodySize: 18,
      bodyWeight: 300,
    },
    metadata: {
      category: 'dark',
      tags: ['dark', 'modern', 'tech'],
      description: 'Modern dark theme with purple accents',
    },
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#74b9ff',
      endColor: '#0984e3',
      angleDeg: 135,
    },
    colorPalette: {
      primary: '#0984e3',
      secondary: '#74b9ff',
      accent: '#00b894',
      text: '#ffffff',
      textSecondary: '#dfe6e9',
      background: '#0984e3',
    },
    decorativeElements: [
      {
        id: 'wave-1',
        shape: 'blob',
        x: 0,
        y: 70,
        width: 100,
        height: 30,
        color: '#00b894',
        opacity: 0.2,
      },
    ],
    typography: {
      titleFont: 'Montserrat, sans-serif',
      titleSize: 45,
      titleWeight: 700,
      bodyFont: 'Montserrat, sans-serif',
      bodySize: 17,
      bodyWeight: 400,
    },
    metadata: {
      category: 'business',
      tags: ['ocean', 'calm', 'professional'],
      description: 'Calming ocean-inspired gradient theme',
    },
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#00b894',
      endColor: '#00a085',
      angleDeg: 90,
    },
    colorPalette: {
      primary: '#00a085',
      secondary: '#00b894',
      accent: '#55efc4',
      text: '#ffffff',
      textSecondary: '#e8f8f5',
      background: '#00a085',
    },
    decorativeElements: [
      {
        id: 'leaf-1',
        shape: 'blob',
        x: 85,
        y: 10,
        width: 20,
        height: 20,
        color: '#55efc4',
        opacity: 0.3,
        rotation: 45,
      },
    ],
    typography: {
      titleFont: 'Open Sans, sans-serif',
      titleSize: 43,
      titleWeight: 600,
      bodyFont: 'Open Sans, sans-serif',
      bodySize: 16,
      bodyWeight: 400,
    },
    metadata: {
      category: 'business',
      tags: ['nature', 'green', 'sustainable'],
      description: 'Fresh green theme perfect for nature and sustainability topics',
    },
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    backgroundStyle: {
      kind: 'radialGradient',
      startColor: '#6c5ce7',
      endColor: '#a29bfe',
      centerX: 50,
      centerY: 50,
    },
    colorPalette: {
      primary: '#6c5ce7',
      secondary: '#a29bfe',
      accent: '#fd79a8',
      text: '#ffffff',
      textSecondary: '#f8f9fa',
      background: '#6c5ce7',
    },
    decorativeElements: [
      {
        id: 'circle-purple-1',
        shape: 'circle',
        x: 10,
        y: 15,
        width: 15,
        height: 15,
        color: '#fd79a8',
        opacity: 0.3,
      },
      {
        id: 'circle-purple-2',
        shape: 'circle',
        x: 75,
        y: 80,
        width: 20,
        height: 20,
        color: '#ffffff',
        opacity: 0.1,
      },
    ],
    typography: {
      titleFont: 'Playfair Display, serif',
      titleSize: 48,
      titleWeight: 700,
      bodyFont: 'Lato, sans-serif',
      bodySize: 18,
      bodyWeight: 400,
    },
    metadata: {
      category: 'creative',
      tags: ['royal', 'elegant', 'creative'],
      description: 'Elegant purple theme with radial gradient',
    },
  },
  {
    id: 'corporate-gray',
    name: 'Corporate Gray',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#2d3436',
      endColor: '#636e72',
      angleDeg: 135,
    },
    colorPalette: {
      primary: '#2d3436',
      secondary: '#636e72',
      accent: '#00b894',
      text: '#ffffff',
      textSecondary: '#dfe6e9',
      background: '#2d3436',
    },
    decorativeElements: [
      {
        id: 'line-corp-1',
        shape: 'line',
        x: 0,
        y: 25,
        width: 100,
        height: 1,
        color: '#00b894',
        opacity: 0.5,
      },
    ],
    typography: {
      titleFont: 'Roboto, sans-serif',
      titleSize: 44,
      titleWeight: 500,
      bodyFont: 'Roboto, sans-serif',
      bodySize: 16,
      bodyWeight: 300,
    },
    metadata: {
      category: 'professional',
      tags: ['corporate', 'formal', 'business'],
      description: 'Professional gray theme for corporate presentations',
    },
  },
  {
    id: 'sunrise-orange',
    name: 'Sunrise Orange',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#fd79a8',
      endColor: '#fdcb6e',
      angleDeg: 45,
    },
    colorPalette: {
      primary: '#e17055',
      secondary: '#fdcb6e',
      accent: '#fd79a8',
      text: '#2d3436',
      textSecondary: '#636e72',
      background: '#fdcb6e',
    },
    decorativeElements: [
      {
        id: 'sun-1',
        shape: 'circle',
        x: 80,
        y: 10,
        width: 25,
        height: 25,
        color: '#fdcb6e',
        opacity: 0.4,
      },
    ],
    typography: {
      titleFont: 'Nunito, sans-serif',
      titleSize: 46,
      titleWeight: 700,
      bodyFont: 'Nunito, sans-serif',
      bodySize: 17,
      bodyWeight: 400,
    },
    metadata: {
      category: 'colorful',
      tags: ['warm', 'sunrise', 'energetic'],
      description: 'Warm sunrise-inspired theme with orange and pink',
    },
  },
  {
    id: 'tech-blue',
    name: 'Tech Blue',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#0984e3',
      endColor: '#00b894',
      angleDeg: 135,
    },
    colorPalette: {
      primary: '#0984e3',
      secondary: '#00b894',
      accent: '#74b9ff',
      text: '#ffffff',
      textSecondary: '#dfe6e9',
      background: '#0984e3',
    },
    decorativeElements: [
      {
        id: 'tech-grid-1',
        shape: 'rect',
        x: 5,
        y: 5,
        width: 90,
        height: 90,
        color: '#74b9ff',
        opacity: 0.05,
      },
    ],
    typography: {
      titleFont: 'Source Sans Pro, sans-serif',
      titleSize: 44,
      titleWeight: 600,
      bodyFont: 'Source Sans Pro, sans-serif',
      bodySize: 16,
      bodyWeight: 400,
    },
    metadata: {
      category: 'professional',
      tags: ['tech', 'modern', 'innovation'],
      description: 'Modern tech theme with blue-green gradient',
    },
  },
  {
    id: 'elegant-gold',
    name: 'Elegant Gold',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#2d3436',
      endColor: '#636e72',
      angleDeg: 180,
    },
    colorPalette: {
      primary: '#2d3436',
      secondary: '#636e72',
      accent: '#fdcb6e',
      text: '#ffffff',
      textSecondary: '#dfe6e9',
      background: '#2d3436',
    },
    decorativeElements: [
      {
        id: 'gold-line-1',
        shape: 'line',
        x: 0,
        y: 15,
        width: 100,
        height: 2,
        color: '#fdcb6e',
        opacity: 0.8,
      },
      {
        id: 'gold-line-2',
        shape: 'line',
        x: 0,
        y: 85,
        width: 100,
        height: 2,
        color: '#fdcb6e',
        opacity: 0.8,
      },
    ],
    typography: {
      titleFont: 'Cormorant Garamond, serif',
      titleSize: 50,
      titleWeight: 700,
      bodyFont: 'Lato, sans-serif',
      bodySize: 18,
      bodyWeight: 400,
    },
    metadata: {
      category: 'professional',
      tags: ['elegant', 'luxury', 'formal'],
      description: 'Elegant dark theme with gold accents',
    },
  },
  {
    id: 'fresh-mint',
    name: 'Fresh Mint',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#55efc4',
      endColor: '#00b894',
      angleDeg: 90,
    },
    colorPalette: {
      primary: '#00b894',
      secondary: '#55efc4',
      accent: '#0984e3',
      text: '#2d3436',
      textSecondary: '#636e72',
      background: '#55efc4',
    },
    decorativeElements: [
      {
        id: 'mint-blob-1',
        shape: 'blob',
        x: 70,
        y: 20,
        width: 30,
        height: 30,
        color: '#ffffff',
        opacity: 0.2,
      },
    ],
    typography: {
      titleFont: 'Poppins, sans-serif',
      titleSize: 45,
      titleWeight: 600,
      bodyFont: 'Poppins, sans-serif',
      bodySize: 17,
      bodyWeight: 400,
    },
    metadata: {
      category: 'creative',
      tags: ['fresh', 'mint', 'light'],
      description: 'Fresh and light mint green theme',
    },
  },
  {
    id: 'fire-red',
    name: 'Fire Red',
    backgroundStyle: {
      kind: 'radialGradient',
      startColor: '#d63031',
      endColor: '#e17055',
      centerX: 50,
      centerY: 50,
    },
    colorPalette: {
      primary: '#d63031',
      secondary: '#e17055',
      accent: '#fdcb6e',
      text: '#ffffff',
      textSecondary: '#ffeaa7',
      background: '#d63031',
    },
    decorativeElements: [
      {
        id: 'fire-circle-1',
        shape: 'circle',
        x: 50,
        y: 50,
        width: 40,
        height: 40,
        color: '#fdcb6e',
        opacity: 0.15,
      },
    ],
    typography: {
      titleFont: 'Bebas Neue, sans-serif',
      titleSize: 52,
      titleWeight: 700,
      bodyFont: 'Roboto, sans-serif',
      bodySize: 18,
      bodyWeight: 400,
    },
    metadata: {
      category: 'colorful',
      tags: ['bold', 'fire', 'energy'],
      description: 'Bold red theme with fiery energy',
    },
  },
  {
    id: 'cloud-white',
    name: 'Cloud White',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#ffffff',
      endColor: '#f1f2f6',
      angleDeg: 135,
    },
    colorPalette: {
      primary: '#2d3436',
      secondary: '#636e72',
      accent: '#0984e3',
      text: '#2d3436',
      textSecondary: '#636e72',
      background: '#ffffff',
    },
    decorativeElements: [
      {
        id: 'cloud-1',
        shape: 'blob',
        x: 10,
        y: 10,
        width: 25,
        height: 15,
        color: '#0984e3',
        opacity: 0.1,
      },
      {
        id: 'cloud-2',
        shape: 'blob',
        x: 70,
        y: 80,
        width: 20,
        height: 12,
        color: '#0984e3',
        opacity: 0.1,
      },
    ],
    typography: {
      titleFont: 'Inter, sans-serif',
      titleSize: 42,
      titleWeight: 600,
      bodyFont: 'Inter, sans-serif',
      bodySize: 16,
      bodyWeight: 400,
    },
    metadata: {
      category: 'minimal',
      tags: ['clean', 'light', 'professional'],
      description: 'Clean white theme with subtle cloud elements',
    },
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#0c2461',
      endColor: '#1e3799',
      angleDeg: 180,
    },
    colorPalette: {
      primary: '#0c2461',
      secondary: '#1e3799',
      accent: '#4a69bd',
      text: '#ffffff',
      textSecondary: '#dfe6e9',
      background: '#0c2461',
    },
    decorativeElements: [
      {
        id: 'star-1',
        shape: 'circle',
        x: 20,
        y: 20,
        width: 3,
        height: 3,
        color: '#ffffff',
        opacity: 0.8,
      },
      {
        id: 'star-2',
        shape: 'circle',
        x: 80,
        y: 30,
        width: 2,
        height: 2,
        color: '#ffffff',
        opacity: 0.6,
      },
      {
        id: 'star-3',
        shape: 'circle',
        x: 60,
        y: 70,
        width: 2.5,
        height: 2.5,
        color: '#ffffff',
        opacity: 0.7,
      },
    ],
    typography: {
      titleFont: 'Montserrat, sans-serif',
      titleSize: 46,
      titleWeight: 700,
      bodyFont: 'Montserrat, sans-serif',
      bodySize: 17,
      bodyWeight: 300,
    },
    metadata: {
      category: 'dark',
      tags: ['midnight', 'deep', 'professional'],
      description: 'Deep midnight blue theme with star accents',
    },
  },
  {
    id: 'pastel-dream',
    name: 'Pastel Dream',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#ffeaa7',
      endColor: '#fab1a0',
      angleDeg: 45,
    },
    colorPalette: {
      primary: '#e17055',
      secondary: '#fab1a0',
      accent: '#74b9ff',
      text: '#2d3436',
      textSecondary: '#636e72',
      background: '#ffeaa7',
    },
    decorativeElements: [
      {
        id: 'pastel-1',
        shape: 'circle',
        x: 15,
        y: 15,
        width: 20,
        height: 20,
        color: '#74b9ff',
        opacity: 0.3,
      },
      {
        id: 'pastel-2',
        shape: 'circle',
        x: 75,
        y: 75,
        width: 18,
        height: 18,
        color: '#fd79a8',
        opacity: 0.3,
      },
    ],
    typography: {
      titleFont: 'Comfortaa, sans-serif',
      titleSize: 44,
      titleWeight: 600,
      bodyFont: 'Comfortaa, sans-serif',
      bodySize: 17,
      bodyWeight: 400,
    },
    metadata: {
      category: 'creative',
      tags: ['pastel', 'soft', 'dreamy'],
      description: 'Soft pastel theme perfect for creative presentations',
    },
  },
  {
    id: 'neon-cyber',
    name: 'Neon Cyber',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#0a0a0a',
      endColor: '#1a1a2e',
      angleDeg: 135,
    },
    colorPalette: {
      primary: '#0a0a0a',
      secondary: '#1a1a2e',
      accent: '#00d4ff',
      text: '#ffffff',
      textSecondary: '#e0e0e0',
      background: '#0a0a0a',
    },
    decorativeElements: [
      {
        id: 'neon-line-1',
        shape: 'line',
        x: 0,
        y: 20,
        width: 100,
        height: 1,
        color: '#00d4ff',
        opacity: 0.6,
      },
      {
        id: 'neon-line-2',
        shape: 'line',
        x: 0,
        y: 80,
        width: 100,
        height: 1,
        color: '#00d4ff',
        opacity: 0.6,
      },
    ],
    typography: {
      titleFont: 'Orbitron, sans-serif',
      titleSize: 48,
      titleWeight: 700,
      bodyFont: 'Roboto Mono, monospace',
      bodySize: 16,
      bodyWeight: 400,
    },
    metadata: {
      category: 'dark',
      tags: ['cyber', 'neon', 'tech'],
      description: 'Cyberpunk-inspired theme with neon accents',
    },
  },
  {
    id: 'spring-garden',
    name: 'Spring Garden',
    backgroundStyle: {
      kind: 'linearGradient',
      startColor: '#a8e6cf',
      endColor: '#dcedc1',
      angleDeg: 90,
    },
    colorPalette: {
      primary: '#4ecdc4',
      secondary: '#a8e6cf',
      accent: '#ff6b6b',
      text: '#2d3436',
      textSecondary: '#636e72',
      background: '#a8e6cf',
    },
    decorativeElements: [
      {
        id: 'flower-1',
        shape: 'circle',
        x: 80,
        y: 15,
        width: 12,
        height: 12,
        color: '#ff6b6b',
        opacity: 0.4,
      },
      {
        id: 'flower-2',
        shape: 'circle',
        x: 20,
        y: 80,
        width: 10,
        height: 10,
        color: '#4ecdc4',
        opacity: 0.4,
      },
    ],
    typography: {
      titleFont: 'Quicksand, sans-serif',
      titleSize: 45,
      titleWeight: 600,
      bodyFont: 'Quicksand, sans-serif',
      bodySize: 17,
      bodyWeight: 400,
    },
    metadata: {
      category: 'creative',
      tags: ['spring', 'garden', 'fresh'],
      description: 'Fresh spring garden theme with pastel colors',
    },
  },
]

